/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import beans.Articulo;
import beans.Ingreso;
import beans.Stock;
import dao.ArticuloDAO;
import dao.FacturaDAO;
import dao.IngresoDAO;
import dao.StockDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.util;

/**
 *
 * @author shoop
 */
public class FrmFactura extends javax.swing.JFrame {
    
   DefaultTableModel model;
   int idFactura;
   int cantidadAntigua;
   int precioAntiguo;
   
   double total = 0;
   double iva = 0;
   double neto = 0;

    /**
     * Creates new form FrmFactura
     */
    public FrmFactura() {
        initComponents();   
         model = (DefaultTableModel) tabFactura.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabFactura = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNroFactura = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        lblNeto = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Factura");

        tabFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Articulo", "Cantidad", "Precio "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFacturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabFactura);

        jLabel1.setText("Nro Factura: ");

        jLabel2.setText("Fecha:");

        lblNroFactura.setForeground(new java.awt.Color(255, 0, 51));

        lblFecha.setForeground(new java.awt.Color(255, 0, 51));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/gtk-refresh.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Neto:");

        jLabel4.setText("Total:");

        jLabel5.setText("I.V.A.:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNroFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 471, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFecha)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblNroFactura)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(lblIVA)
                        .addComponent(lblTotal)
                        .addComponent(lblNeto)))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFacturaMouseClicked
        int rows = tabFactura.getSelectedRow();
        cantidadAntigua = Integer.parseInt(model.getValueAt(rows, 2).toString());
        this.precioAntiguo = Integer.parseInt(model.getValueAt(rows, 3).toString());
    }//GEN-LAST:event_tabFacturaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int rows = tabFactura.getSelectedRow();
        
        int codArt = codigoArt(model.getValueAt(rows, 1).toString()); //necesito
        int cantidad = Integer.parseInt(model.getValueAt(rows, 2).toString());
        String cate = this.catArt(model.getValueAt(rows, 1).toString());//necesito
        int precio = Integer.parseInt(model.getValueAt(rows, 3).toString());
        
        IngresoDAO id = new IngresoDAO();
        int resp = JOptionPane.showConfirmDialog(null, "Desea Actualizar la cantidad " + cantidadAntigua + "(antigua) por " + cantidad+"(nueva) y el precio "+this.precioAntiguo+"(antiguo) por "+precio+"(nuevo)", "Confirmacion", JOptionPane.YES_NO_OPTION);
        
        if (resp == 0) {
            if (id.Editar(idFactura, codArt, cate, cantidad, precio)) {

                StockDAO sd = new StockDAO();
                ArrayList<Stock> stocks = sd.getStock2(cate);
                int newCantidad = 0;

                if (cantidad > cantidadAntigua) {
                    cantidad = cantidad - cantidadAntigua;
                    for (Stock stock : stocks) {
                        int b = stock.getCodigoArt();
                        if (b == codArt) {
                            int a = stock.getStock();
                            newCantidad = a + cantidad;
                        }
                    }

                    sd.actualizar(newCantidad, codArt, cate);

                } else {
                    cantidad = cantidadAntigua - cantidad;
                    for (Stock stock : stocks) {
                        
                        int b = stock.getCodigoArt();
                        if (b == codArt) {
                            int a = stock.getStock();
                            newCantidad = a - cantidad;
                        }
                    }
                    sd.actualizar(newCantidad, codArt, cate);
                }

                JOptionPane.showMessageDialog(null, id.getMessage(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error al actualizar", "Informacion", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFactura().setVisible(true);
            }
        });
    }
    
    public void cargaTabla (int idFactura, int nroFactura, String fecha){
        
        
        lblNroFactura.setText(String.valueOf(nroFactura));
        lblFecha.setText(fecha);
                
        this.idFactura = idFactura;
        
        IngresoDAO id = new IngresoDAO();
        ArrayList <Ingreso> ingresos = id.getIngresoDetalle(idFactura);
        
        for (Ingreso ingreso : ingresos) {
            Object filas [] = new Object [4];
            filas [0] = ingreso.getCodigoArt();
            filas [1] = articulo(ingreso.getCodigoArt(), ingreso.getCategoria());
            filas [2] = ingreso.getCantidad();
            filas [3] = ingreso.getPrecioUnitario();
            
            model.addRow(filas);
            
            total += ingreso.getPrecioUnitario();
            
        }
        
        tabFactura.setModel(model);
        
        neto = total/1.19;
        iva = (total * 19) / 100;
        
         util u = new util();
        
        lblNeto.setText("$ " + u.formatearNumero(String.valueOf(Math.round(neto))));
        lblIVA.setText("$ " + u.formatearNumero(String.valueOf(Math.round(iva))));
        lblTotal.setText("$ " + u.formatearNumero(String.valueOf(Math.round(total))));
         
        
        
    }
    
    public String articulo (int cod, String cat){
        ArticuloDAO ad = new ArticuloDAO();
        ArrayList <Articulo> articulos = ad.getAxC(cat);
        
        String nombre = "";
        
        for (Articulo articulo : articulos) {
            if(articulo.getCodigoArt() == cod ){
                nombre = articulo.getNombreArt();
                break;
            }
        }
        return nombre;
    }
    public int codigoArt(String nombre) {
        ArticuloDAO ad = new ArticuloDAO();
        ArrayList<Articulo> articulos = ad.getArticulos();
        int cod = 0;
        for (Articulo articulo : articulos) {
            if (articulo.getNombreArt().equals(nombre)) {
                cod = articulo.getCodigoArt();
                break;
            }
        }
        return cod;
    }
    
    public String catArt(String nombre) {
        ArticuloDAO ad = new ArticuloDAO();
        ArrayList<Articulo> articulos = ad.getArticulos();
        String cod = "";
        for (Articulo articulo : articulos) {
            if (articulo.getNombreArt().equals(nombre)) {
                cod = articulo.getCategoria();
                break;
            }
        }
        return cod;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblNeto;
    private javax.swing.JLabel lblNroFactura;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tabFactura;
    // End of variables declaration//GEN-END:variables
}
