/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import javax.swing.ImageIcon;

/**
 *
 * @author Marcos Pulgar
 */
public class FrmPrincipal extends javax.swing.JFrame {
    
    
    IfrmNuevoDepartamento depa;
    IfrmNuevoProveedor np ;
    IfrmNuevaFactura nf;
    IfrmNuevoArticulo na;
    IfrmNuevaEntrega ne;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        depa = new IfrmNuevoDepartamento();
        np = new IfrmNuevoProveedor();
        nf = new IfrmNuevaFactura();
        na = new IfrmNuevoArticulo ();
        ne = new IfrmNuevaEntrega();
        this.setIconImage (new ImageIcon(getClass().getResource("/gui/icono16.png")).getImage());
        
   
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        desk = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        PmnuArchivo = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuNuevoArticulo = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuNuevoProveedor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuNuevaFactura = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuNuevaEntrega = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuNuevoDepa = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuFacturaxFecha = new javax.swing.JMenuItem();
        mnuExistencias = new javax.swing.JMenuItem();
        mnuLibro = new javax.swing.JMenuItem();
        mnuGuias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de Existencias  -  ExisSoft");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        desk.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        PmnuArchivo.setText("Archivo");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/document-delete-31021.png"))); // NOI18N
        jMenuItem2.setText("Anular Factura");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        PmnuArchivo.add(jMenuItem2);

        jMenuItem5.setText("Borrar Entrega");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        PmnuArchivo.add(jMenuItem5);

        jMenuItem3.setText("Cambiar Clave");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        PmnuArchivo.add(jMenuItem3);
        PmnuArchivo.add(jSeparator5);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Salir-Blanco.png"))); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        PmnuArchivo.add(mnuSalir);

        jMenuBar1.add(PmnuArchivo);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/agregar-nuevo-documento-de-archivo-mas-icono-6249-48.png"))); // NOI18N
        jMenu1.setText("Agregar");

        mnuNuevoArticulo.setText("Articulo");
        mnuNuevoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoArticuloActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevoArticulo);
        jMenu1.add(jSeparator1);

        mnuNuevoProveedor.setText("Proveedor");
        mnuNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevoProveedor);
        jMenu1.add(jSeparator2);

        mnuNuevaFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnuNuevaFactura.setText("Factura");
        mnuNuevaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaFacturaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevaFactura);
        jMenu1.add(jSeparator3);

        mnuNuevaEntrega.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnuNuevaEntrega.setText("Entrega");
        mnuNuevaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaEntregaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevaEntrega);
        jMenu1.add(jSeparator4);

        mnuNuevoDepa.setText("Departamento");
        mnuNuevoDepa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoDepaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNuevoDepa);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ver");

        mnuFacturaxFecha.setText("Facturas por fecha");
        mnuFacturaxFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacturaxFechaActionPerformed(evt);
            }
        });
        jMenu2.add(mnuFacturaxFecha);

        mnuExistencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mnuExistencias.setText("Control de Existencias");
        mnuExistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExistenciasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuExistencias);

        mnuLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnuLibro.setText("Libro de Existencias");
        mnuLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLibroActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLibro);

        mnuGuias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuGuias.setText("Guia de Entregas");
        mnuGuias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuiasActionPerformed(evt);
            }
        });
        jMenu2.add(mnuGuias);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Infromacion");

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icono16.png"))); // NOI18N
        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desk, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNuevoDepaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoDepaActionPerformed
        
        desk.add(depa);
        depa.show();
    }//GEN-LAST:event_mnuNuevoDepaActionPerformed

    private void mnuNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoProveedorActionPerformed
        
        desk.add(np);
        np.show();
    }//GEN-LAST:event_mnuNuevoProveedorActionPerformed

    private void mnuNuevaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaFacturaActionPerformed
        
        desk.add(nf);
        nf.show();
    }//GEN-LAST:event_mnuNuevaFacturaActionPerformed

    private void mnuNuevoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoArticuloActionPerformed
        
        desk.add(na);
        na.show();
    }//GEN-LAST:event_mnuNuevoArticuloActionPerformed

    private void mnuNuevaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaEntregaActionPerformed
        
        desk.add(ne);
        ne.show();
    }//GEN-LAST:event_mnuNuevaEntregaActionPerformed

    private void mnuFacturaxFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacturaxFechaActionPerformed
        IfrmFacturaXFecha iff = new IfrmFacturaXFecha();
        
        desk.add(iff);
        iff.show();
    }//GEN-LAST:event_mnuFacturaxFechaActionPerformed

    private void mnuExistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExistenciasActionPerformed
        IfrmProductos ip = new IfrmProductos();
        desk.add(ip);
        ip.show();
    }//GEN-LAST:event_mnuExistenciasActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        IfrmAnularFactura af = new IfrmAnularFactura();
        desk.add(af);
        af.show();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibroActionPerformed
        IfrmDetalle detalle = new IfrmDetalle();
        desk.add(detalle);
        detalle.show();
    }//GEN-LAST:event_mnuLibroActionPerformed

    private void mnuGuiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuiasActionPerformed
        IfrmGuiasEntregas entregas = new IfrmGuiasEntregas();
        desk.add(entregas);
        entregas.show();
    }//GEN-LAST:event_mnuGuiasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        IfrmCambioContraseña icc = new IfrmCambioContraseña();
        desk.add(icc);
        icc.show();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        IfrmAbout ab = new IfrmAbout();
        desk.add(ab);
//        ab.setUI(null);
        ab.show();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        IfrmBorrarEntrega ibe = new IfrmBorrarEntrega();
        desk.add(ibe);
        ibe.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu PmnuArchivo;
    private javax.swing.JDesktopPane desk;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JMenuItem mnuExistencias;
    private javax.swing.JMenuItem mnuFacturaxFecha;
    private javax.swing.JMenuItem mnuGuias;
    private javax.swing.JMenuItem mnuLibro;
    private javax.swing.JMenuItem mnuNuevaEntrega;
    private javax.swing.JMenuItem mnuNuevaFactura;
    private javax.swing.JMenuItem mnuNuevoArticulo;
    private javax.swing.JMenuItem mnuNuevoDepa;
    private javax.swing.JMenuItem mnuNuevoProveedor;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
