/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Articulo;
import beans.Departamento;
import beans.Stock;
import dao.ArticuloDAO;
import dao.DepartamentoDAO;
import dao.EntregaDAO;
import dao.StockDAO;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Pulgar
 */
public class IfrmNuevaEntrega extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    private String cat;

    /**
     * Creates new form IfrmNuevaEntrega
     */
    public IfrmNuevaEntrega() {
        initComponents();
        cargaCbo();
        model = (DefaultTableModel) tabArticulos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        cboDepartamento = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        dteFechaI = new com.toedter.calendar.JDateChooser();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        cboArticulos = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        chkIva = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        cboCat = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabArticulos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnAgregarEntrega = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Realizar Entrega");
        setToolTipText("");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Departamento: ");

        jLabel2.setText("Fecha: ");

        dteFechaI.setMaximumSize(new java.awt.Dimension(7483647, 7483647));

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cboDepartamento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(dteFechaI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(dteFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dteFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Articulo: ");

        jLabel7.setText("Cantidad: ");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/agregar-nuevo-documento-de-archivo-mas-icono-6249-48.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel8.setText("Precio: ");

        chkIva.setText("Incluir iva.");

        jLabel3.setText("Categoria:");

        cboCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione", "2204001", "2204007", "2204009" }));
        cboCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCatActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(cboArticulos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(btnAgregar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(txtPrecio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(chkIva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(cboCat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkIva)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCat, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cboCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tabArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Articulo", "Articulo", "Categoria", "Cantidad", "Precio", "Seccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabArticulos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabArticulos);

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar Seleccion");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregarEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/agregar-nuevo-documento-de-archivo-mas-icono-6249-48.png"))); // NOI18N
        btnAgregarEntrega.setText("Agregar Entrega");
        btnAgregarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEntregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLayeredPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarEntrega)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregarEntrega))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargaCbo() {
        DepartamentoDAO dd = new DepartamentoDAO();
        ArrayList<Departamento> departamentos = dd.getDepartamentos();

        for (Departamento departamento : departamentos) {
            cboDepartamento.addItem(departamento.getNombreDepa());
        }
    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ArticuloDAO ad = new ArticuloDAO(); //traer articulos recorrerlos e igualarlo con el codigo 
        ArrayList<Articulo> articulos = ad.getArticulos();

        Object filas[] = new Object[6];
        int precio = Integer.parseInt(txtPrecio.getText());
        if (chkIva.isSelected()) {
            precio = precio + ((precio * 19) / 100);
        }

        filas[0] = buscaCodigo(cboArticulos.getSelectedItem().toString());
        filas[1] = cboArticulos.getSelectedItem();
        filas[2] = cboCat.getSelectedItem();
        filas[3] = txtCantidad.getText();
        filas[4] = precio;
        filas[5] = cboDepartamento.getSelectedItem().toString();

        model.addRow(filas);
        tabArticulos.setModel(model);


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabArticulos.getModel();
        int a = tabArticulos.getSelectedRow();
        model.removeRow(a);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEntregaActionPerformed

        int rows1 = model.getRowCount();

        String dia = String.valueOf(dteFechaI.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = String.valueOf(dteFechaI.getCalendar().get(Calendar.MONTH) + 1);
        String anio = String.valueOf(dteFechaI.getCalendar().get(Calendar.YEAR));
        String fecha = anio + "-" + mes + "-" + dia;
        
        int aviso = 0;

        for (int i = 0; i < rows1; i++) {

            int stockA = validar(i);

            if (stockA >= 0) {

                EntregaDAO ed = new EntregaDAO();

                int rows = model.getRowCount();

                    int cantidad = Integer.parseInt(model.getValueAt(i, 3).toString());
                    int codigoArt = Integer.parseInt(model.getValueAt(i, 0).toString());
                    int precio = Integer.parseInt(model.getValueAt(i, 4).toString());
                    String cat = model.getValueAt(i, 2).toString();
                    String depa = model.getValueAt(i,5).toString();
                    if (ed.agregar(codigoArt, depa, fecha, cantidad, precio, cat)) {
                        StockDAO sd = new StockDAO();

                        ArrayList<Stock> stocks = sd.getStock2(model.getValueAt(i, 2).toString());

                        int newCantidad = 0;
                        for (Stock stock : stocks) {
                            int b = stock.getCodigoArt();
                            if (b == codigoArt && stock.getCategoria().equals(cat)) {
                                int a = stock.getStock();
                                newCantidad = a - cantidad;
                                
                                sd.actualizar(newCantidad, codigoArt, cat);
                                
                                break;
                            }
                        }
                    


                    } else {
                        String nombre = tabArticulos.getValueAt(i, 1).toString();
                        JOptionPane.showMessageDialog(null, "Producto  " + nombre + ", No fue entregado\n"+ed.getMessage());
                        aviso = 1;
                    }
                

                
            } else {
                aviso = 1;
                String nombre = tabArticulos.getValueAt(i, 1).toString();
                JOptionPane.showMessageDialog(null, "El articulo '" + nombre + "', supera el stock", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        if (aviso == 0) {
            JOptionPane.showMessageDialog(null, "Tarea realizada", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        
        int rowsTotal = model.getRowCount();
        
        for (int i = 0; i <= rowsTotal; i++) {
            model.removeRow(0);
        }

        cboDepartamento.setSelectedIndex(0);

        txtCantidad.setText("");
        txtPrecio.setText("");


    }//GEN-LAST:event_btnAgregarEntregaActionPerformed

    private void cboCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCatActionPerformed
        cboArticulos.removeAllItems();

        ArticuloDAO ad = new ArticuloDAO();
        ArrayList<Articulo> articulos = ad.getAparaCombo(cboCat.getSelectedItem().toString());

        for (Articulo articulo : articulos) {
            cboArticulos.addItem(articulo.getNombreArt());
        }
    }//GEN-LAST:event_cboCatActionPerformed

    public int validar(int i) {
        StockDAO sd = new StockDAO();

        int rows = model.getRowCount();
        int newCantidad = 0;
        for (i = i; i < rows; i++) {
            ArrayList<Stock> stocks = sd.getStock2(model.getValueAt(i, 2).toString());
            int cantidad = Integer.parseInt(model.getValueAt(i, 3).toString());
            int codigoArt = Integer.parseInt(model.getValueAt(i, 0).toString());
            String cate = model.getValueAt(i, 2).toString();

            for (Stock stock : stocks) {
                int b = stock.getCodigoArt();
                if (b == codigoArt && stock.getCategoria().equals(cate)) {
                    int a = stock.getStock();
                    newCantidad = a - cantidad;
                    break;
                }
            }

        }
        return newCantidad;
    }

//    public void agregaEntrega(){
//        EntregaDAO ed = new EntregaDAO();
//        
//        
//        DefaultTableModel model = (DefaultTableModel) tabArticulos.getModel();
//        
//        String dia = String.valueOf(dteFechaI.getCalendar().get(Calendar.DAY_OF_MONTH));
//        String mes = String.valueOf(dteFechaI.getCalendar().get(Calendar.MONTH)+1);
//        String anio = String.valueOf(dteFechaI.getCalendar().get(Calendar.YEAR));
//        String fecha = anio + "-" + mes + "-" + dia;
//        String depa = cboDepartamento.getSelectedItem().toString();
//        
//        int rows = model.getRowCount();
//        
//        for (int i = 0; i < rows; i++) {
//            int cantidad = Integer.parseInt(model.getValueAt(i, 3).toString());
//            int codigoArt = Integer.parseInt(model.getValueAt(i, 0).toString());
//            int precio = Integer.parseInt(model.getValueAt(i, 4).toString());
//            ed.agregar(codigoArt, depa, fecha, cantidad, precio);
//        }
//    }
    public int buscaCodigo(String nombre) {

        ArticuloDAO ad = new ArticuloDAO();
        ArrayList<Articulo> articulos = ad.getAxC(cboCat.getSelectedItem().toString());
        int codigo = 0;
        for (Articulo articulo : articulos) {
            if (nombre.equals(articulo.getNombreArt())) {
                codigo = articulo.getCodigoArt();
                break;
            }
        }
        return codigo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarEntrega;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox cboArticulos;
    private javax.swing.JComboBox cboCat;
    private javax.swing.JComboBox cboDepartamento;
    private javax.swing.JCheckBox chkIva;
    private com.toedter.calendar.JDateChooser dteFechaI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabArticulos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
