/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Articulo;
import beans.Entrega;
import beans.Ingreso;
import beans.ReporteProductos;
import beans.Stock;
import dao.ArticuloDAO;
import dao.EntregaDAO;
import dao.IngresoDAO;
import dao.StockDAO;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import util.Imprimir;

/**
 *
 * @author Marcos Pulgar
 */
public class IfrmProductos extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    int folio;
    String cate;
    

    /**
     * Creates new form IfrmProductos
     */
    public IfrmProductos() {
        initComponents();
        model = (DefaultTableModel) tabArticulos.getModel();
//        cargarTabla();

    }

//    public void cargarTabla (){
//        ArticuloDAO ad = new ArticuloDAO(); 
//        ArrayList <Articulo> articulos = ad.getArticulos2();
//        
//         
//        
//        int totalfilas = model.getRowCount();
//        
//        for (int i = 0; i < totalfilas; i++) {
//            model.removeRow(0);
//        }
//        
//        for (Articulo articulo : articulos) {
//            Object filas [] = new Object [5];
//            filas [0] = articulo.getCodigoArt();
//            filas [1] = articulo.getNombreArt();
//            filas [2] = buscarStock(articulo.getCodigoArt());
//            filas [3] = saldo(articulo.getCodigoArt());
//            filas [4] = saldo(articulo.getCodigoArt())*buscarStock(articulo.getCodigoArt());
//            
//            model.addRow(filas);
//        }
//        tabArticulos.setModel(model);
//    }
    public int saldo(int cod, String cat) {
        IngresoDAO ed = new IngresoDAO();
        ArrayList<Ingreso> ingresos = ed.getIngresoxC(cat);
        ArticuloDAO ad = new ArticuloDAO();
        ArrayList<Articulo> articulos = ad.getAxC(cat);
        int precio = 0;
        int i = 0;
        for (Ingreso ingreso : ingresos) {

            if (ingreso.getCodigoArt() == cod) {
                precio = precio + ingreso.getPrecioUnitario();
                i++;
            }
        }

        if (precio != 0) {
            precio = (precio / i);
            return precio;
        } else {
            return 0;
        }
    }

    public int buscarStock(int cod, String cat) {
        StockDAO sd = new StockDAO();
        ArrayList<Stock> stocks = sd.getStock2(cat);
        int total = 0;
        for (Stock stock : stocks) {
            if (cod == stock.getCodigoArt()) {

                total = stock.getStock();

            }
        }
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabArticulos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        txtnOfFiscalizador = new javax.swing.JTextField();
        txtnOfFinanzas = new javax.swing.JTextField();
        txtgOfFinanzas = new javax.swing.JTextField();
        txtgOfFiscalizador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtgJefeAdm = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnJefeAdm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboCat = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Existencias");

        jLayeredPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Articulo", "Stock", "Precio Unitario", "Saldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabArticulosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabArticulos);

        jLabel3.setText("Grado Of. Fiscalizador:");

        jLabel2.setText("Nombre Of. Fiscalizador:");

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images.png"))); // NOI18N
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Of. Finanzas:");

        jLabel5.setText("Grado Of. Finanzas:");

        txtgJefeAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgJefeAdmActionPerformed(evt);
            }
        });

        jLabel6.setText("Grado Jefe Adm:");

        jLabel7.setText("Nombre Jefe Adm:");

        jLabel1.setText("Categoria: ");

        cboCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "2204001", "2204007", "2204009" }));
        cboCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCatActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icono16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtnOfFiscalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(23, 23, 23)
                                    .addComponent(txtnOfFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtnJefeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtgOfFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtgOfFiscalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtgJefeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(btnImprimir)
                        .addContainerGap())
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCat, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(20, 20, 20))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnOfFiscalizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnOfFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtnJefeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtgJefeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtgOfFiscalizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtgOfFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnImprimir)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnImprimir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtnOfFiscalizador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtnOfFinanzas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtgOfFinanzas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtgOfFiscalizador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtgJefeAdm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtnJefeAdm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cboCat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        List productos = new ArrayList();
        int totalArt = tabArticulos.getRowCount();
        int saldototal = 0;

        for (int i = 0; i < totalArt; i++) {
            ReporteProductos lista = new ReporteProductos();
            lista.setFolio(tabArticulos.getValueAt(i, 0).toString());
            lista.setNombre(tabArticulos.getValueAt(i, 1).toString());
            lista.setStock(tabArticulos.getValueAt(i, 2).toString());
            lista.setPrecio(tabArticulos.getValueAt(i, 3).toString());
            lista.setSaldo(tabArticulos.getValueAt(i, 4).toString());
            saldototal = saldototal + Integer.parseInt(tabArticulos.getValueAt(i, 4).toString());
            productos.add(lista);

        }

        String ruta = System.getProperty("user.dir") + "\\reportes\\ReporteProductos.jasper";

        Map parametro = new HashMap();
        int total = tabArticulos.getRowCount();
        parametro.put("nOfFiscalizador", txtnOfFiscalizador.getText());
        parametro.put("gOfFiscalizador", txtgOfFiscalizador.getText());
        parametro.put("nOfFinanzas", txtnOfFinanzas.getText());
        parametro.put("gOfFinanzas", txtgOfFinanzas.getText());
        parametro.put("nJAdmin", txtnJefeAdm.getText());
        parametro.put("gJAdmin", txtgJefeAdm.getText());

        NumberFormat formatea = NumberFormat.getNumberInstance();
        int valor = saldototal;
        formatea.setMaximumFractionDigits(0);
        String nuevototal = formatea.format(valor);

        parametro.put("total", nuevototal);

        if (cboCat.getSelectedItem().toString().equals("2204001")) {
            parametro.put("titulo", "Materiales de Oficina");
        }
        if (cboCat.getSelectedItem().toString().equals("2204007")) {
            parametro.put("titulo", "Materiales y Utiles de Aseo");
        }
        if (cboCat.getSelectedItem().toString().equals("2204009")) {
            parametro.put("titulo", "Insumos Computacionales");
        }

        Imprimir imp = new Imprimir();
        imp.Impresion(ruta, parametro, productos);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtgJefeAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgJefeAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgJefeAdmActionPerformed

    private void cboCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCatActionPerformed
        ArticuloDAO ad = new ArticuloDAO();
        ArrayList<Articulo> articulos = ad.getAxC(cboCat.getSelectedItem().toString());

        int totalfilas = model.getRowCount();

        for (int i = 0; i < totalfilas; i++) {
            model.removeRow(0);
        }

        for (Articulo articulo : articulos) {
            Object filas[] = new Object[5];
            filas[0] = articulo.getCodigoArt();
            filas[1] = articulo.getNombreArt();
            filas[2] = buscarStock(articulo.getCodigoArt(), cboCat.getSelectedItem().toString());
            filas[3] = saldo(articulo.getCodigoArt(), cboCat.getSelectedItem().toString());
            filas[4] = saldo(articulo.getCodigoArt(), cboCat.getSelectedItem().toString()) * buscarStock(articulo.getCodigoArt(), cboCat.getSelectedItem().toString());

            model.addRow(filas);

        }
        tabArticulos.setModel(model);
    }//GEN-LAST:event_cboCatActionPerformed

    private void tabArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabArticulosMouseClicked
        int row = tabArticulos.getSelectedRow();
        folio = Integer.parseInt(model.getValueAt(row, 0).toString());
        cate = cboCat.getSelectedItem().toString();
    }//GEN-LAST:event_tabArticulosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StockDAO sd = new StockDAO();
        int row = tabArticulos.getSelectedRow();
        int stock = Integer.parseInt(tabArticulos.getValueAt(row, 2).toString());
        
         int resp = JOptionPane.showConfirmDialog(null, "Desea Actualizar el stock del folio  " + folio + " por " +stock, "Confirmacion", JOptionPane.YES_NO_OPTION);

        if (resp == 0) {
            if (sd.actualizar(stock, folio, cate)) {
                JOptionPane.showMessageDialog(null, "Stock Actualizado", "Ok", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Error al Actualizar Stock", "Error", JOptionPane.ERROR_MESSAGE );
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox cboCat;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabArticulos;
    private javax.swing.JTextField txtgJefeAdm;
    private javax.swing.JTextField txtgOfFinanzas;
    private javax.swing.JTextField txtgOfFiscalizador;
    private javax.swing.JTextField txtnJefeAdm;
    private javax.swing.JTextField txtnOfFinanzas;
    private javax.swing.JTextField txtnOfFiscalizador;
    // End of variables declaration//GEN-END:variables
}
