/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Articulo;
import beans.Departamento;
import beans.Entrega;
import beans.Stock;
import dao.ArticuloDAO;
import dao.DepartamentoDAO;
import dao.EntregaDAO;
import dao.StockDAO;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author shoop
 */
public class IfrmBorrarEntrega extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrmBorrarEntrega
     */
    public IfrmBorrarEntrega() {
        initComponents();
        cboSecciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboCate = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboArticulos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cboDepartamento = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        dteFecha = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Fecha:");

        jLabel2.setText("Categoria:");

        cboCate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "2204001", "2204007", "2204009" }));
        cboCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCateActionPerformed(evt);
            }
        });

        jLabel3.setText("Articulo:");

        jLabel4.setText("Seccion");

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(dteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboCate, 0, 193, Short.MAX_VALUE)
                    .addComponent(cboArticulos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dteFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(cboArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jButton1))
                            .addComponent(cboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCateActionPerformed
        cboArticulos.removeAllItems();

        ArticuloDAO ad = new ArticuloDAO();
        ArrayList<Articulo> articulos = ad.getAparaCombo(cboCate.getSelectedItem().toString());

        for (Articulo articulo : articulos) {
            cboArticulos.addItem(articulo.getNombreArt());
        }
    }//GEN-LAST:event_cboCateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String dia = String.valueOf(dteFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = String.valueOf(dteFecha.getCalendar().get(Calendar.MONTH) + 1);
        String anio = String.valueOf(dteFecha.getCalendar().get(Calendar.YEAR));
        String fecha = anio + "-" + mes + "-" + dia;
        String depa = cboDepartamento.getSelectedItem().toString();
        int codArt = this.buscaCodigo(cboArticulos.getSelectedItem().toString());
        String cate = cboCate.getSelectedItem().toString();

        int resp = JOptionPane.showConfirmDialog(null, "Desea Borrar esta entrega?","Confirmacion", JOptionPane.YES_NO_OPTION);

        if (resp == 0) {
            EntregaDAO ed = new EntregaDAO();
            if (ed.BorrarEntrega(fecha, depa, cate, codArt)) {
                
                ArrayList<Entrega> entregas = ed.getStockEntregas(fecha, codArt, cate);
                
                int StockA = 0;
                
                for (Entrega entrega : entregas) {
                    StockA = entrega.getCantidadArt();
                }
                
                this.ActualizaStock(codArt, cate, StockA);
                
                JOptionPane.showMessageDialog(null, "Entrega Borrada", "Ok", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error al Borrar entrega, Verifique datos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    public void cboSecciones() {
        DepartamentoDAO dd = new DepartamentoDAO();
        ArrayList<Departamento> departamentos = dd.getDepartamentos();

        for (Departamento departamento : departamentos) {
            cboDepartamento.addItem(departamento.getNombreDepa());
        }
    }

    public int buscaCodigo(String nombre) {

        ArticuloDAO ad = new ArticuloDAO();
        ArrayList<Articulo> articulos = ad.getAxC(cboCate.getSelectedItem().toString());
        int codigo = 0;
        for (Articulo articulo : articulos) {
            if (nombre.equals(articulo.getNombreArt())) {
                codigo = articulo.getCodigoArt();
                break;
            }
        }
        return codigo;
    }

    protected void ActualizaStock (int codArt, String cate, int StockA){
        
        
        StockDAO sd = new StockDAO();
        
        int newCantidad = StockA+ sd.getStockUnico(cate, codArt).getStock();
        
        sd.actualizar(newCantidad, codArt, cate);
        
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboArticulos;
    private javax.swing.JComboBox cboCate;
    private javax.swing.JComboBox cboDepartamento;
    private com.toedter.calendar.JDateChooser dteFecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
